<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jogo de escrever</title>
</head>
<body>
    <main>
        <div class="console-box">
            <?php foreach($arrayAssociativo->messages as $mensagem): ?>
            <p><?= $mensagem ?></p>
            <?php endforeach ?>
        </div>
        <div class="form-group">
            <form>
                <input type="text" name="comando"/>
                <input type="submit"/>
            </form>
        </div>
    </main>
</body>
</html>